emwiki/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
]

emwiki/article/urls.py
from django.urls import path

from . import views

app_name = 'article'
urlpatterns = [
    path('proofs/<str:article_name>/<str:proof_name>', views.ProofView.as_view(), name='proofs'),
    path('refs/<str:article_name>/<str:ref_name>', views.RefView.as_view(), name='refs'),
    path('bibs', views.BibView.as_view(), name='bibs'),
    path('comments', views.CommentView.as_view(), name='comments'),
    path('names', views.ArticleIndexView.as_view(), name='names'),
    path('htmls', views.ArticleHtmlView.as_view(), name='htmls'),
    path('<str:name_or_filename>', views.ArticleView.as_view(), name='index'),
]

emwiki/emwiki/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.generic import RedirectView

urlpatterns = [
    path('search/', include('search.urls')),
    path('graph/', include('graph.urls')),
    path('article/', include('article.urls')),
    path('symbol/', include('symbol.urls')),
    path('accounts/', include('accounts.urls')),
    path('explanation/', include('explanation.urls')),
    path('settings/', include('settings.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

emwiki/graph/urls.py
from django.urls import path

from . import views

app_name = 'graph'
urlpatterns = [
    path('', views.GraphView.as_view(), name='index'),
]

emwiki/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('usage/', views.UsageView.as_view(), name='usage')
]

emwiki/symbol/urls.py
from django.urls import path

from . import views

app_name = 'symbol'
urlpatterns = [
    path('names', views.SymbolIndexView.as_view(), name='names'),
    path('htmls', views.SymbolHtmlView.as_view(), name='htmls'),
    path('<path:name>', views.SymbolView.as_view(), name='index'),
]

emwiki/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>emwiki</title>


  <!-- Vue 2 -->
  <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>

  <!-- Vue Router -->
  <script src="https://unpkg.com/vue-router@3.0.7/dist/vue-router.js"></script>

  <!-- Vuetify -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/@mdi/font@6.5.95/css/materialdesignicons.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/vuetify@2.6.4/dist/vuetify.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
  <script src="https://cdn.jsdelivr.net/npm/vuetify@2.6.4/dist/vuetify.js"></script>

  <!-- Axios -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

  {% block head %}{% endblock %}
</head>

<body>
  {% csrf_token %}
  <div id="app">
    <v-app>
      <v-navigation-drawer app v-model="drawerExists" :width="drawerWidth"
        :disable-resize-watcher="disableResizeWatcher">
        {% block drawer %}{% endblock %}
      </v-navigation-drawer>

      <v-app-bar app height="64px">
        <v-app-bar-nav-icon v-if="menuButton" @click="drawerExists = !drawerExists"></v-app-bar-nav-icon>
        <v-toolbar-title>emwiki</v-toolbar-title>

        <v-spacer></v-spacer>

        <v-btn href="{% url 'home:index' %}" text>Home</v-btn>
        <v-btn href="{% url 'explanation:index' %}" text>Document</v-btn>
        {% if user.is_authenticated %}
        <v-btn href="{% url 'settings:develop' %}" text>Develop</v-btn>
        {% endif %}
        <v-btn href="{% url 'article:index' 'abcmiz_0' %}" text>Article</v-btn>
        <v-btn href="{% url 'symbol:index' '0' %}" text>Symbol</v-btn>
        <v-btn href="{% url 'article:index' 'abcmiz_0' %}?target=theorem" text>Theorem</v-btn>
        <v-btn href="{% url 'graph:index' %}" text>Graph</v-btn>
        {% if user.is_authenticated %}
        <v-btn href="{% url 'settings:index' %}" text>Settings</v-btn>
        {% endif %}
        <v-menu offset-y>
          {% if user.is_authenticated %}
          <template v-slot:activator="{ on, attrs }">
            <v-btn v-bind="attrs" v-on="on" text>
              {{ user.get_username }}
            </v-btn>
          </template>
          <v-list>
            <v-list-item-group>
              <v-list-item href="{% url 'accounts:user_detail' user.pk %}">
                User information
              </v-list-item>
              <v-list-item href="{% url 'accounts:logout' %}">
                Logout
              </v-list-item>
            </v-list-item-group>
          </v-list>
          {% else %}
          <template v-slot:activator="{ on, attrs }">
            <v-btn v-bind="attrs" v-on="on" text>
              Account
            </v-btn>
          </template>
          <v-list>
            <v-list-item-group>
              <v-list-item href="{% url 'accounts:signup' %}">
                Sign up
              </v-list-item>
              <v-list-item href="{% url 'accounts:login' %}">
                Login
              </v-list-item>
            </v-list-item-group>
          </v-list>
          {% endif %}
        </v-menu>
      </v-app-bar>
      <splitter v-if="drawerExists" :drawer-width.sync="drawerWidth" :drawer-exists.sync="drawerExists"></splitter>
      <v-main>
        {% block content %}{% endblock %}
      </v-main>
    </v-app>
  </div>

  <!-- base CSS, JavaScript -->
  <link rel='stylesheet' href="{% static 'css/base.css' %}" type='text/css'>
  </link>
  {% block foot %}
  <script src="{% static 'js/main.js' %}"></script>
  {% endblock %}
</body>

</html>