emwiki/emwiki/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.generic import RedirectView

urlpatterns = [
    path('search/', include('search.urls')),
    path('graph/', include('graph.urls')),
    path('article/', include('article.urls')),
    path('symbol/', include('symbol.urls')),
    path('accounts/', include('accounts.urls')),
    path('explanation/', include('explanation.urls')),
    path('settings/', include('settings.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

emwiki/explanation/urls.py
from django.urls import path
from . import views

app_name = 'explanation'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create', views.CreateView.as_view(), name='create'),
    path('explanation', views.ExplanationView.as_view(), name='explanation'),
    path('titles', views.ExplanationTitleView.as_view(), name='titles'),
    path('detail/<str:title>', views.DetailView.as_view(), name='detail'),
    path('detail/<str:title>/update', views.UpdateView.as_view(), name='update'),
    path('detail/<str:title>/delete', views.DeleteView.as_view(), name='delete'),
    path('<str:name_or_filename>', views.Redirect_ArticleView.as_view(), name='article'),
    path('proofs/<str:article_name>/<str:proof_name>', views.Redirect_ProofView.as_view(), name='proofs'),
    path('refs/<str:article_name>/<str:ref_name>', views.Redirect_RefView.as_view(), name='refs'),
    path('detail/proofs/<str:article_name>/<str:proof_name>', views.Detail_ProofView.as_view(), name='detail_proofs'),
    path('detail/refs/<str:article_name>/<str:ref_name>', views.Detail_RefView.as_view(), name='detail_refs'),
    path('detail/<str:title>/<str:name_or_filename>', views.Update_ArticleView.as_view(), name='update'),
    path('detail/<str:title>/proofs/<str:article_name>/<str:proof_name>', views.Update_ProofView.as_view(), name='update_proofs'),
    path('detail/<str:title>/refs/<str:article_name>/<str:ref_name>', views.Update_RefView.as_view(), name='update_refs'),
]

emwiki/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('usage/', views.UsageView.as_view(), name='usage')
]

emwiki/explanation/models.py
import os

from django.db import models
from django.conf import settings
from django.utils import timezone


class Explanation(models.Model):
    title = models.CharField(max_length=200, unique=True)
    text = models.TextField()
    preview = models.TextField(default='no preview')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(null=True, blank=True)
    related_articles = models.ManyToManyField('article.Article', related_name='explanations')

    def __str__(self):
        return f"{self.title}, {self.author}"

    def save(self, *args, **kwargs):
        self.updated_at = timezone.now()
        return super().save(*args, **kwargs)

    def get_explanationfile_path(self):
        return os.path.join(settings.EMWIKI_CONTENTS_EXPLANATON_DIR, 'explanation.txt')

    def commit_explanation_creates(self):
        commit_message = f'Create {self.title}\n {self.author}\n'
        settings.EMWIKI_CONTENTS_EXPLANATION_REPO.git.add(self.get_explanationfile_path())
        settings.EMWIKI_CONTENTS_EXPLANATION_REPO.index.commit(commit_message)

    def commit_explanation_changes(self):
        commit_message = f'Update {self.title}\n {self.author}\n'
        settings.EMWIKI_CONTENTS_EXPLANATION_REPO.git.add(self.get_explanationfile_path())
        settings.EMWIKI_CONTENTS_EXPLANATION_REPO.index.commit(commit_message)

emwiki/explanation/views.py
import json
import re
from natsort import humansorted
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, Http404
from .models import Explanation
from article.models import Article
from django.core.exceptions import ValidationError
from django.views import generic
from django.views.generic.base import TemplateView
from django.views.generic import View
from django.urls import reverse, reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


extra_context = {
    "context_for_js": {
        'base_uri': reverse_lazy('explanation:index'),
        'titles_uri': reverse_lazy('explanation:titles'),
        'article_base_uri': reverse_lazy('article:names'),
        'article_html_base_uri': reverse_lazy('article:htmls'),
        'article_index_uri': reverse_lazy('article:index'),
        'article_proof_uri': reverse_lazy('article:proofs'),
        'article_ref_uri': reverse_lazy('article:refs'),
    }
}


class IndexView(TemplateView):
    template_name = 'explanation/index.html'
    extra_context = {
        "context_for_js": {
            'base_uri': reverse_lazy('explanation:index'),
            'titles_uri': reverse_lazy('explanation:titles'),
        }
    }


class CreateView(generic.CreateView):
    model = Explanation
    fields = ['title', 'text', 'author', 'created_at', 'updated_at']
    extra_context = {
        'context_for_js': {
            'base_uri': reverse_lazy('explanation:index'),
            'titles_uri': reverse_lazy('explanation:titles'),
            'explanation_uri': reverse_lazy('explanation:explanation'),
            'article_names_uri': reverse_lazy('article:names'),
            'article_html_base_uri': reverse_lazy('article:htmls'),
        }
    }


class ExplanationTitleView(View):
    def get(self, request):
        explanations = humansorted(list(Explanation.objects.all()), key=lambda a: a.title)
        return JsonResponse({'index': [
            dict(id=explanation.id, title=explanation.title) for explanation in explanations
        ]})


class ExplanationView(View):
    def get(self, request, title=None):
        if 'title' in request.GET:
            selectedExplanation = get_object_or_404(Explanation, title=request.GET.get('title'))
            selected_text = selectedExplanation.text
            selected_preview = selectedExplanation.preview
            return JsonResponse({'text': selected_text, 'preview': selected_preview})

        elif 'article_name' in request.GET:
            explanations = Explanation.objects.filter(related_articles=request.GET.get('article_name'))
            related_titles = []
            for explanation in explanations:
                related_titles.append(explanation.title)
            return JsonResponse({"related_documents": related_titles})

        else:
            explanations = humansorted(list(Explanation.objects.all()), key=lambda a: a.title)
            return JsonResponse({'explanation': [
                dict(id=explanation.id, title=explanation.title, text=explanation.text) for explanation in explanations
            ]})

    def validate_explanation_title(self, blog_id, title):
        if not title:
            raise ValidationError('This field is required.')

        if len(title) > 200:
            raise ValidationError('Title must be 200 characters or less.')

        if Explanation.objects.exclude(id=blog_id).filter(title=title).exists():
            raise ValidationError('Title must be unique.')

    @method_decorator(login_required)
    def post(self, request):
        post = json.loads(request.body)
        posted_id = post.get('id', None)
        posted_title = post.get('title', None)
        posted_text = post.get('text', None)
        posted_preview = post.get('preview', None)

        if request.user.is_authenticated:
            username = request.user.username
            User = get_user_model()
            user = User.objects.get(username=username)

        try:
            self.validate_explanation_title(posted_id, posted_title)
        except ValidationError as e:
            errors = e.messages[0]
            return JsonResponse({'errors': errors}, status=400)

        createExplanation = Explanation.objects.create(title=posted_title, text=posted_text, preview=posted_preview, author=user)

        pattern = r"embed\(/article/([^#]+)#.*\)"
        article_names = re.findall(pattern, posted_text)
        for article_name in article_names:
            try:
                article = get_object_or_404(Article, name=article_name)
                createExplanation.related_articles.add(article)
            except Http404:
                print(f"Article with name {article_name} not found.")

        createExplanation.commit_explanation_creates()

        return redirect('explanation:index')


class DetailView(View):
    def get(self, request, title):
        explanations = humansorted(list(Explanation.objects.all()), key=lambda a: a.title)
        title_exists = any(explanation.title == title for explanation in explanations)
        if title_exists:
            context = dict()
            context["context_for_js"] = {
                'explanation_detail_uri': reverse('explanation:detail', kwargs=dict(title="temp")).replace('temp', ''),
                'base_uri': reverse_lazy('explanation:index'),
                'titles_uri': reverse_lazy('explanation:titles'),
                'explanation_uri': reverse_lazy('explanation:explanation'),
            }
            return render(request, 'explanation/explanation_detail.html', context)
        else:
            target_url = reverse('article:index', kwargs={'name_or_filename': title})
            return redirect(target_url)


class UpdateView(View):
    def get(self, request, title):
        context = dict()
        context["context_for_js"] = {
            'explanation_detail_uri': reverse('explanation:detail', kwargs=dict(title="temp")).replace('temp', ''),
            'base_uri': reverse_lazy('explanation:index'),
            'titles_uri': reverse_lazy('explanation:titles'),
            'explanation_uri': reverse_lazy('explanation:explanation'),
            'article_html_base_uri': reverse_lazy('article:htmls'),
        }
        return render(request, 'explanation/explanation_change.html', context)

    def put(self, request, title):
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'Authentication required'}, status=401)

        post = json.loads(request.body)
        updatedExplanation = Explanation.objects.get(title=title)
        User = get_user_model()
        username = request.user.username
        update_author = User.objects.get(username=username)
        updatedExplanation.text = post.get('text', None)
        updatedExplanation.preview = post.get('preview', None)
        updatedExplanation.author = update_author

        updatedExplanation.related_articles.clear()

        pattern = r"embed\(/article/([^#]+)#.*\)"
        article_names = re.findall(pattern, updatedExplanation.text)
        for article_name in article_names:
            try:
                article = get_object_or_404(Article, name=article_name)
                updatedExplanation.related_articles.add(article)
            except Http404:
                print(f"Article with name {article_name} not found.")

        updatedExplanation.save()
        updatedExplanation.commit_explanation_changes()
        return render(request, 'explanation/index.html')


class DeleteView(View):
    def get(self, request, title):
        context = dict()
        context["context_for_js"] = {
            'explanation_detail_uri': reverse('explanation:detail', kwargs=dict(title="temp")).replace('temp', ''),
            'base_uri': reverse_lazy('explanation:index'),
            'titles_uri': reverse_lazy('explanation:titles'),
            'explanation_uri': reverse_lazy('explanation:explanation'),
        }
        return render(request, 'explanation/explanation_confirm_delete.html', context)

    def delete(self, request, title):
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'Authentication required'}, status=401)

        deleteExplanation = Explanation.objects.get(title=title)
        deleteExplanation.delete()
        return render(request, 'explanation/index.html')


class Redirect_ArticleView(View):
    def get(self, request, name_or_filename):
        target_url = reverse('article:index', kwargs={'name_or_filename': name_or_filename})
        return redirect(target_url)


class Redirect_ProofView(View):
    def get(self, request, article_name, proof_name):
        target_url = reverse('article:proofs', kwargs={'article_name': article_name, 'proof_name': proof_name})
        return redirect(target_url)


class Redirect_RefView(View):
    def get(self, request, article_name, ref_name):
        target_url = reverse('article:refs', kwargs={'article_name': article_name, 'ref_name': ref_name})
        return redirect(target_url)


class Detail_ProofView(View):
    def get(self, request, article_name, proof_name):
        target_url = reverse('article:proofs', kwargs={'article_name': article_name, 'proof_name': proof_name})
        return redirect(target_url)


class Detail_RefView(View):
    def get(self, request, article_name, ref_name):
        target_url = reverse('article:refs', kwargs={'article_name': article_name, 'ref_name': ref_name})
        return redirect(target_url)


class Update_ArticleView(View):
    def get(self, request, name_or_filename, title):
        target_url = reverse('article:index', kwargs={'name_or_filename': name_or_filename})
        return redirect(target_url)


class Update_ProofView(View):
    def get(self, request, article_name, proof_name, title):

emwiki/explanation/templates/explanation/explanation_change.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{{ context_for_js|json_script:"context" }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
<link rel='stylesheet' href="{% static 'explanation/css/index.css' %}" type='text/css'>
</link>

<!-- js-cookie -->
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>

<script type="text/javascript" src="{% static 'explanation/js/mathjax.js'%}"></script>
<script src="{% static 'article/js/htmlized_mml.js' %}"></script>


<!-- Markdown -->
<script src="https://unpkg.com/marked@0.3.6/lib/marked.js"></script>
<script src="https://unpkg.com/vue-md-editor/dist/vue-editor.min.js"></script>
<script>
    marked.setOptions({
        renderer: new marked.Renderer(),
        gfm: true,
        tables: true,
        breaks: false,
        pedantic: false,
        sanitize: false, // IMPORTANT, because we do MathJax before markdown,
        //            however we do escaping in 'CreatePreview'.
        smartLists: true,
        smartypants: false
    });
</script>

<!-- MathJax -->
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
{% endblock %}

{% block drawer %}
<explanation-drawer />
{% endblock %}
{% block content %}
<router-view />
{% endblock %}

{% block foot %}
<script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js"
    integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.4.0/marked.min.js"></script>
<!-- App -->
<script src="{% static 'explanation/js/app.js' %}" type="module"></script>
{% endblock %}

emwiki/explanation/templates/explanation/explanation_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{{ context_for_js|json_script:"context" }}
<link rel='stylesheet' href="{% static 'explanation/css/index.css' %}" type='text/css'>
</link>
{% endblock %}

{% block drawer %}
<explanation-drawer />
{% endblock %}

{% block content %}
<router-view />
{% endblock %}

{% block foot %}
<script src="{% static 'explanation/js/app.js' %}" type="module"></script>
{% endblock %}

emwiki/explanation/templates/explanation/explanation_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{{ context_for_js|json_script:"context" }}
<link rel='stylesheet' href="{% static 'explanation/css/index.css' %}" type='text/css'>
</link>

<!-- js-cookie -->
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
<script type="text/javascript" src="{% static 'explanation/js/mathjax.js'%}"></script>
<script src="{% static 'article/js/htmlized_mml.js' %}"></script>


<!-- Markdown -->
<script src="https://unpkg.com/marked@0.3.6/lib/marked.js"></script>
<script src="https://unpkg.com/vue-md-editor/dist/vue-editor.min.js"></script>
<script>
    marked.setOptions({
        renderer: new marked.Renderer(),
        gfm: true,
        tables: true,
        breaks: false,
        pedantic: false,
        sanitize: false, // IMPORTANT, because we do MathJax before markdown,
        //            however we do escaping in 'CreatePreview'.
        smartLists: true,
        smartypants: false
    });
</script>

<!-- MathJax -->
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
{% endblock %}

{% block drawer %}
<explanation-drawer />
{% endblock %}
{% block content %}
<router-view />
{% endblock %}

{% block foot %}
<script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js"
    integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.4.0/marked.min.js"></script>
<!-- App -->
<script src="{% static 'explanation/js/app.js'%}" type="module"></script>
{% endblock %}

emwiki/explanation/templates/explanation/explanation_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{{ context_for_js|json_script:"context" }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
<link rel='stylesheet' href="{% static 'explanation/css/index.css' %}" type='text/css'>
</link>
<script type="text/javascript" src="{% static 'explanation/js/mathjax.js'%}"></script>
<script src="{% static 'article/js/htmlized_mml.js' %}"></script>

<!-- Markdown -->
<script src="https://unpkg.com/marked@0.3.6/lib/marked.js"></script>
<script src="https://unpkg.com/vue-md-editor/dist/vue-editor.min.js"></script>
<script>
    marked.setOptions({
        renderer: new marked.Renderer(),
        gfm: true,
        tables: true,
        breaks: false,
        pedantic: false,
        sanitize: false, // IMPORTANT, because we do MathJax before markdown,
        //            however we do escaping in 'CreatePreview'.
        smartLists: true,
        smartypants: false
    });
</script>

<!-- MathJax -->
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
{% endblock %}

{% block drawer %}
<explanation-drawer />
{% endblock %}

{% block content %}
<create-explanation />
{% endblock %}

{% block foot %}
<script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js"
    integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.4.0/marked.min.js"></script>
<script src="{% static 'explanation/js/app.js' %}" type="module"></script>
{% endblock %}

emwiki/explanation/templates/explanation/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{{ context_for_js|json_script:"context" }}
<!-- js-cookie -->
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>

<link rel='stylesheet' href="{% static 'explanation/css/index.css' %}" type='text/css'>
</link>
{% endblock %}

{% block drawer %}
<explanation-drawer />
{% endblock %}

{% block content %}
<v-container fluid>
    <h1 class="display-3">Document</h1>
    <p>This page allows you to create MML Explanatory documents in Markdown format.</p>
    {% if user.is_authenticated %}
    <p>
        <v-btn outlined href="{% url 'explanation:create' %}" text>Create New</v-btn>
    </p>
    {% endif %}
</v-container>
{% endblock %}

{% block foot %}
<!-- App -->
<script src="{% static 'explanation/js/app.js'%}" type="module"></script>
{% endblock %}