emwiki/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
]

emwiki/emwiki/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.generic import RedirectView

urlpatterns = [
    path('search/', include('search.urls')),
    path('graph/', include('graph.urls')),
    path('article/', include('article.urls')),
    path('symbol/', include('symbol.urls')),
    path('accounts/', include('accounts.urls')),
    path('explanation/', include('explanation.urls')),
    path('settings/', include('settings.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

emwiki/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('usage/', views.UsageView.as_view(), name='usage')
]

emwiki/accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.validators import UnicodeUsernameValidator


class CustomUserManager(UserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        if not username:
            raise ValueError('The given username must be set')
        if not email:
            raise ValueError('The given email must be set')
        username = self.model.normalize_username(username)
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(username, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    email = models.EmailField(
        _('email address'),
        help_text=_('Required.')
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

emwiki/accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm,
    PasswordResetForm, SetPasswordForm
)

from accounts.models import User


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Email', required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class MyLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class MyPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = "form-control"


class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class EmailChangeForm(forms.ModelForm):
    """メールアドレス変更フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = User
        fields = ('username',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

emwiki/accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from accounts.forms import (
    MyLoginForm, MyUserCreationForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, EmailChangeForm,
    UserUpdateForm
)
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.shortcuts import redirect, resolve_url
from django.core.signing import SignatureExpired, BadSignature, loads, dumps
from django.http import HttpResponseBadRequest

from .models import User


class SignUpView(generic.CreateView):
    form_class = MyUserCreationForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'


class Login(LoginView):
    form_class = MyLoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'accounts/logout.html'


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('accounts:password_change_done')
    template_name = 'accounts/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'accounts/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'accounts/mail_template/password_reset/subject.txt'
    email_template_name = 'accounts/mail_template/password_reset/message.txt'
    template_name = 'accounts/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'accounts/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'accounts/password_reset_complete.html'


class EmailChange(LoginRequiredMixin, generic.FormView):
    """メールアドレスの変更"""
    template_name = 'accounts/email_change_form.html'
    form_class = EmailChangeForm

    def form_valid(self, form):
        user = self.request.user
        new_email = form.cleaned_data['email']

        # URLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(new_email),
            'user': user,
        }

        subject = render_to_string(
            'accounts/mail_template/email_change/subject.txt',
            context
        )
        message = render_to_string(
            'accounts/mail_template/email_change/message.txt',
            context
        )
        send_mail(subject, message, None, [new_email])

        return redirect('accounts:email_change_done')


class EmailChangeDone(LoginRequiredMixin, generic.TemplateView):
    """メールアドレスの変更メールを送ったよ"""
    template_name = 'accounts/email_change_done.html'


class EmailChangeComplete(LoginRequiredMixin, generic.TemplateView):
    """リンクを踏んだ後に呼ばれるメアド変更ビュー"""
    template_name = 'accounts/email_change_complete.html'
    # デフォルトでは1日以内
    timeout_seconds = getattr(
        settings,
        'ACTIVATION_TIMEOUT_SECONDS',
        60 * 60 * 24
    )

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            new_email = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            print('Bad token')
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            User.objects.filter(email=new_email, is_active=False).delete()
            request.user.email = new_email
            request.user.save()
            return super().get(request, **kwargs)


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'accounts/user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'accounts/user_form.html'

    def get_success_url(self):
        return resolve_url('accounts:user_detail', pk=self.kwargs['pk'])

emwiki/accounts/templates/accounts/email_change_complete.html
{% extends "base.html" %}
{% block content %}
<v-container>
    <p class="text-h4">Your email address has been changed.</p>
</v-container>
{% endblock %}

emwiki/accounts/templates/accounts/email_change_done.html
{% extends "base.html" %}
{% block content %}
<v-container>
    <p class="text-h4">Click on the link in the email to change your email address.</p>
</v-container>
{% endblock %}

emwiki/accounts/templates/accounts/email_change_form.html
{% extends "base.html" %}
{% block content %}
<v-row justify="center mt-5">
    <v-col
      cols="12"
      sm="10"
      md="8"
      lg="6"
    >
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary">New email</p>
                    <div class="red--text">{{ form.non_field_errors }}</div>
                    {% for field in form %}
                        <v-text-field
                          name="{{ field.name }}"
                          label="{{ field.label }}"
                          type="email"
                          required
                        ></v-text-field>
                        <div class="red--text">{{ field.errors }}</div>
                    {% endfor %}
                    {% csrf_token %}
                </v-card-text>
                <v-divider class="mt-6"></v-divider>
                <v-card-actions class="d-flex flex-row-reverse">
                    <v-btn type="submit" block>Submit</v-btn>
                </v-card-actions>
            </form>
      </v-card>
    </v-col>
</v-row>
{% endblock %}

emwiki/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<v-row justify="center mt-5">
    <v-col
      cols="12"
      sm="10"
      md="8"
      lg="6"
    >
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary">Login</p>
                    <div class="red--text">{{ form.non_field_errors }}</div>
                    {% for field in form %}
                        {% if field.name == "password" %}
                            <v-text-field
                              name="{{ field.name }}"
                              label="{{ field.label }}"
                              type="password"
                              required
                            ></v-text-field>
                            <div class="red--text">{{ field.errors }}</div>
                         {% else %}
                             <v-text-field
                             name="{{ field.name }}"
                             label="{{ field.label }}"
                             type="text"
                             required
                             ></v-text-field>
                            <div class="red--text">{{ field.errors }}</div>
                        {% endif %}
                    {% endfor %}
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}" />
                </v-card-text>
                <v-divider class="mt-6"></v-divider>
                <v-card-actions class="d-flex flex-row-reverse">
                    <v-btn type="submit" block>Login</v-btn>
                </v-card-actions>
                <v-divider class="mt-6"></v-divider>
                <v-card-actions class="d-flex justify-center">
                    <v-btn href="{% url 'accounts:signup' %}">Sign up</v-btn>
                    <v-btn href="{% url 'accounts:password_reset' %}">Password reset</v-btn>
                </v-card-actions>
            </form>
      </v-card>
    </v-col>
</v-row>
{% endblock %}

emwiki/accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% block content %}
<v-container>
    <p class="text-h4">Logged out</p>
</v-container>
{% endblock %}

emwiki/accounts/templates/accounts/password_change.html
{% extends "base.html" %}
{% block content %}
<v-row justify="center mt-5">
    <v-col
      cols="12"
      sm="10"
      md="8"
      lg="6"
    >
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary">Change password</p>
                    <div class="red--text">{{ form.non_field_errors }}</div>
                    {% for field in form %}
                        <v-text-field
                          name="{{ field.name }}"
                          label="{{ field.label }}"
                          type="password"
                          hint="It must contain at least 8 characters."
                          required
                        ></v-text-field>
                        <div class="red--text">{{ field.errors }}</div>
                    {% endfor %}
                    {% csrf_token %}
                </v-card-text>
                <v-divider class="mt-6"></v-divider>
                <v-card-actions>
                    <v-btn type="submit" block>Submit</v-btn>
                </v-card-actions>
            </form>
      </v-card>
    </v-col>
</v-row>
{% endblock %}

emwiki/accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}
{% block content %}
<v-container>
    <p class="text-h4">Password has been changed.</p>
    <v-btn href="{% url 'accounts:login' %}">Login</v-btn>
</v-container>
{% endblock %}

emwiki/accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
<v-container>
    <p class="text-h4">Your password has been reset.</p>
    <v-btn href="{% url 'accounts:login' %}">Login</v-btn>
</v-container>
{% endblock %}

emwiki/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
<v-row justify="center mt-5">
    <v-col
      cols="12"
      sm="10"
      md="8"
      lg="6"
    >
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary">New password</p>
                    <div class="red--text">{{ form.non_field_errors }}</div>
                    {% for field in form %}
                        <v-text-field
                          name="{{ field.name }}"
                          label="{{ field.label }}"
                          type="password"
                          hint="It must contain at least 8 characters."
                          required
                        ></v-text-field>
                        <div class="red--text">{{ field.errors }}</div>
                    {% endfor %}
                    {% csrf_token %}
                </v-card-text>
                <v-divider class="mt-6"></v-divider>
                <v-card-actions>
                    <v-btn type="submit" block>Submit</v-btn>
                </v-card-actions>
            </form>
      </v-card>
    </v-col>
</v-row>
{% endblock %}

emwiki/accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<v-container>
    <p class="text-h4">Check your inbox for an email from us with a link to reset your password.</p>
</v-container>
{% endblock %}

emwiki/accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}
{% block content %}

<v-row justify="center mt-5">
    <v-col
      cols="12"
      sm="10"
      md="8"
      lg="6"
    >
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary">Password Reset</p>
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        <v-text-field
                          name="{{ field.name }}"
                          label="{{ field.label }}"
                          type="email"
                          required
                        ></v-text-field>
                        <div class="red--text">{{ field.errors }}</div>
                    {% endfor %}
                    {% csrf_token %}
                </v-card-text>
                <v-divider class="mt-6"></v-divider>
                <v-card-actions>
                    <v-btn type="submit" block>Send</v-btn>
                </v-card-actions>
            </form>
      </v-card>
    </v-col>
</v-row>
{% endblock %}

emwiki/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<v-row justify="center mt-5">
    <v-col
      cols="12"
      sm="10"
      md="8"
      lg="6"
    >
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary">Sign up</p>
                    <div class="red--text">{{ form.non_field_errors }}</div>
                    {% for field in form %}
                        {% if "password" in field.name %}
                            <v-text-field
                              name="{{ field.name }}"
                              label="{{ field.label }}"
                              type="password"
                              hint="It must contain at least 8 characters."
                              required
                            ></v-text-field>
                            <div class="red--text">{{ field.errors }}</div>
                        {% elif field.name == "email" %}
                            <v-text-field
                            name="{{ field.name }}"
                            label="{{ field.label }}"
                            type="email"
                            required
                            ></v-text-field>
                           <div class="red--text">{{ field.errors }}</div>
                         {% else %}
                             <v-text-field
                             name="{{ field.name }}"
                             label="{{ field.label }}"
                             type="text"
                             required
                             ></v-text-field>
                            <div class="red--text">{{ field.errors }}</div>
                        {% endif %}
                    {% endfor %}
                    {% csrf_token %}
                </v-card-text>
                <v-divider class="mt-6"></v-divider>
                <v-card-actions>
                    <v-btn type="submit" block>Submit</v-btn>
                </v-card-actions>
            </form>
      </v-card>
    </v-col>
</v-row>
{% endblock %}

emwiki/accounts/templates/accounts/user_detail.html
{% extends "base.html" %}
{% block content %}
<v-row justify="center mt-5">
    <v-col
      cols="12"
      sm="10"
      md="8"
      lg="6"
    >
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary mb-12">User Information</p>
                    <v-row class="d-flex">
                        <v-col class="font-weight-black">Username:</v-col>
                        <v-col class="mr-auto">{{ user.username }}</v-col>
                        <v-col>
                            <v-btn class="ml-auto" href="{% url 'accounts:user_update' user.pk %}">
                                <v-icon>mdi-pencil</v-icon>
                            </v-btn>
                        </v-col>
                    </v-row>
                    <v-divider class="mb-3"></v-divider>
                    <v-row class="d-flex">
                        <v-col class="font-weight-black">Email:</v-col>
                        <v-col class="mr-auto">{{ user.email }}</v-col>
                        <v-col>
                            <v-btn class="ml-auto" href="{% url 'accounts:email_change' %}">
                                <v-icon>mdi-pencil</v-icon>
                            </v-btn>
                        </v-col>
                    </v-row>
                    <v-divider class="mb-3"></v-divider>
                    <v-row class="d-flex">
                        <v-col class="font-weight-black">Password:</v-col>
                        <v-col class="mr-auto">●●●●●●●●●●●</v-col>
                        <v-col>
                            <v-btn class="ml-auto" href="{% url 'accounts:password_change' %}">
                                <v-icon>mdi-pencil</v-icon>
                            </v-btn>
                        </v-col>
                    </v-row>
                    <v-divider class="mb-3"></v-divider>
                </v-card-text>
            </form>
      </v-card>
    </v-col>
</v-row>
{% endblock %}

emwiki/accounts/templates/accounts/user_form.html
{% extends "base.html" %}
{% block content %}

<v-row justify="center mt-5">
    <v-col
      cols="12"
      sm="10"
      md="8"
      lg="6"
    >
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary">New Username</p>
                    <div class="red--text">{{ form.non_field_errors }}</div>
                    {% for field in form %}
                        <v-text-field
                          name="{{ field.name }}"
                          label="{{ field.label }}"
                          type="text"
                          required
                        ></v-text-field>
                        <div class="red--text">{{ field.errors }}</div>
                    {% endfor %}
                    {% csrf_token %}
                </v-card-text>
                <v-divider class="mt-6"></v-divider>
                <v-card-actions class="d-flex flex-row-reverse">
                    <v-btn type="submit" block>Submit</v-btn>
                </v-card-actions>
            </form>
      </v-card>
    </v-col>
</v-row>
{% endblock %}