emwiki/emwiki/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.generic import RedirectView

urlpatterns = [
    path('search/', include('search.urls')),
    path('graph/', include('graph.urls')),
    path('article/', include('article.urls')),
    path('symbol/', include('symbol.urls')),
    path('accounts/', include('accounts.urls')),
    path('explanation/', include('explanation.urls')),
    path('settings/', include('settings.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

emwiki/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('usage/', views.UsageView.as_view(), name='usage')
]

emwiki/settings/urls.py
from django.urls import path
from . import views

app_name = 'settings'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('registration', views.RegistrationView.as_view(), name='registration'),
    path('change', views.ChangeView.as_view(), name='change'),
    path('develop', views.DevelopView.as_view(), name='develop'),
]

emwiki/settings/models.py
from django.db import models
from django.conf import settings


class Settings(models.Model):
    github_id = models.CharField(max_length=100, default='', blank=True)
    repository_name = models.CharField(max_length=100, default='', blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.user.username}, {self.github_id}"

emwiki/settings/views.py
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect
from .models import Settings
from django.contrib.auth import get_user_model


class IndexView(TemplateView):
    template_name = 'settings/index.html'

    def get(self, request):
        user = get_user_model().objects.get(username=request.user.username)
        settings = Settings.objects.filter(user=user).first()

        if settings is not None:
            id = settings.github_id
            repository_name = settings.repository_name
            return render(request, 'settings/index.html', {'github_id': id, 'repository_name': repository_name})
        else:
            return render(request, 'settings/index.html')


class RegistrationView(TemplateView):
    template_name = 'settings/settings_registration.html'

    def post(self, request):
        if request.method == 'POST':
            user_name = get_user_model().objects.get(username=request.user.username)
            id = request.POST.get('github_id')
            repository_name = request.POST.get('repository_name')
            new_settings = Settings.objects.create(user=user_name, github_id=id, repository_name=repository_name)
            new_settings.save()

            return redirect('settings:index')


class ChangeView(TemplateView):
    template_name = 'settings/settings_change.html'

    def get(self, request):
        user = get_user_model().objects.get(username=request.user.username)
        settings = Settings.objects.filter(user=user).first()

        return render(request, 'settings/settings_change.html', {'settings': settings})

    def post(self, request):
        if request.method == 'POST':
            change_settings = Settings.objects.filter(user=get_user_model().objects.get(username=request.user.username)).first()
            change_settings.github_id = request.POST.get('github_id')
            change_settings.repository_name = request.POST.get('repository_name')
            change_settings.save()

            return redirect('settings:index')


class DevelopView(TemplateView):
    template_name = 'settings/develop.html'

    def get(self, request):
        settings = Settings.objects.filter(user=get_user_model().objects.get(username=request.user.username)).first()

        if settings is not None:
            id = settings.github_id
            repository_name = settings.repository_name

            return render(request, 'settings/develop.html', {'github_id': id, 'repository_name': repository_name})
        else:
            return render(request, 'settings/develop.html')

emwiki/settings/templates/settings/develop.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<v-row justify="center mt-5">
    <v-col cols="12" sm="10" md="8" lg="7">
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary mb-5">Preparation</p>
                    <ol class="text-h6 text--primary mb-5">
                        <li>Create your GitHub account <a
                                href="https://docs.github.com/get-started/start-your-journey/creating-an-account-on-github"
                                target="_blank">ℹ️</a>.</li>
                        <li>Fork <a href="https://github.com/mimosa-project/mizar-server-contents" target="_blank">the
                                Mizar server
                                contents repository</a> beforehand <a
                                href="{% static 'settings/img/fork_repository.png' %}" target="_blank">ℹ️</a>.<br>
                            Note: When forking, please deselect the option "Copy the main branch only" to ensure that
                            all branches are created.</li>
                        <li>Set your GitHub ID and GitHub repository name on the <a href="{% url 'settings:index' %}"
                                target="_blank">settings
                                page</a>.<br>
                            Your forked repository URL should be: https://github.com/&lt;GitHub ID&gt;/&lt;GitHub
                            repository name&gt;</li>
                        {% if github_id %}
                        <li>Transition to VSCode for the Web by clicking the <a
                                href="https://github.dev/{{github_id}}/{{repository_name}}" target="_blank"
                                rel="noopener noreferrer">
                                [DEVELOP]
                            </a>button.</li>
                        {% else %}
                        <li>Transition to VSCode for the Web by clicking the [DEVELOP] button.</li>
                        {% endif %}
                        <li>Install the "emvscode-web" VSCode for the Web extension <a
                                href="{% static 'settings/img/emvscode-web_install.png' %}" target="_blank">ℹ️</a>.</li>
                        <li>Obtain an OAuth Token (a personal access token (classic, scope: repo)) at <a
                                href="https://github.com/settings/tokens" target="_blank">GitHub</a> <a
                                href="https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic"
                                target="_blank">ℹ️</a>.</li>
                        <li>Configure the OAuth Token for VSCode for the Web <a
                                href="{% static 'settings/img/emvscode-web_OAuth_token.png' %}" target="_blank">ℹ️</a>.
                        </li>
                        <li>To execute a Mizar compilation, create a .miz file in the text folder. With the file open,
                            start the command palette and select "Mizar: Mizar Compile". Click <a
                                href="{% static 'settings/txt/Mizar_sample.txt' %}" target="_blank">here</a> for a
                            sample code to
                            verify the operation.
                        </li>
                    </ol>
                </v-card-text>
                {% if github_id %}
                <a href="https://github.dev/{{github_id}}/{{repository_name}}" target="_blank"
                    rel="noopener noreferrer">
                    <v-btn block>Develop</v-btn>
                </a>
                {% else %}
                <v-btn block>Develop</v-btn>
                {% endif %}
            </form>
        </v-card>
    </v-col>
</v-row>
{% endblock %}

emwiki/settings/templates/settings/index.html
{% extends "base.html" %}
{% block content %}
<v-row justify="center mt-5">
    <v-col cols="12" sm="10" md="8" lg="6">
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary mb-12">Settings</p>
                    {% if github_id %}
                    {% else %}
                    <p class="text-h6 text--primary mb-12">※Please set the following items</p>
                    {% endif %}
                    <v-row class="d-flex">
                        <v-col class="font-weight-black">GitHub ID: </v-col>
                        <v-col class="mr-auto">{{ github_id }}</v-col>
                    </v-row>
                    <v-divider class="mb-3"></v-divider>
                    <v-row class="d-flex">
                        <v-col class="font-weight-black">GitHub repository name:</v-col>
                        <v-col class="mr-auto">{{ repository_name }}</v-col>
                    </v-row>
                    <v-divider class="mb-3"></v-divider>
                </v-card-text>
            </form>
            {% if github_id %}
            <v-btn href="{% url 'settings:change' %}" block>Change</v-btn>
            {% else %}
            <v-btn href="{% url 'settings:registration' %}" block>Registration</v-btn>
            {% endif %}
        </v-card>
    </v-col>
</v-row>
{% endblock %}

emwiki/settings/templates/settings/settings_change.html
{% extends "base.html" %}

{% block content %}
<v-row justify="center mt-5">
    <v-col cols="12" sm="10" md="8" lg="6">
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary mb-12">New Settings</p>
                    <v-text-field id="github_id" name="github_id" label="GitHub ID" type="text" required
                        value="{{settings.github_id}}"></v-text-field>
                    <v-text-field id="repository_name" name="repository_name" label="GitHub repository name" type="text"
                        required value="{{settings.repository_name}}"></v-text-field>
                    {% csrf_token %}
                </v-card-text>
                <v-btn type="submit" block>Change</v-btn>
            </form>
        </v-card>
    </v-col>
</v-row>
{% endblock %}

emwiki/settings/templates/settings/settings_registration.html
{% extends "base.html" %}
{% block content %}
<v-row justify="center mt-5">
    <v-col cols="12" sm="10" md="8" lg="6">
        <v-card ref="form">
            <form action="" method="post">
                <v-card-text>
                    <p class="text-h4 text--primary mb-12">New Settings</p>
                    <v-text-field id="github_id" name="github_id" label="GitHub ID" type="text" required></v-text-field>
                    <v-text-field id="repository_name" name="repository_name" label="GitHub repository name" type="text"
                        required></v-text-field>
                    {% csrf_token %}
                </v-card-text>
                <v-btn type="submit" block>Registration</v-btn>
            </form>
        </v-card>
    </v-col>
</v-row>
{% endblock %}